version: '3.8'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:16
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env

  auth_api:
    build: ./
    env_file: .env
    volumes:
      - static:/static
    depends_on:
      - db

  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
    depends_on:
      - db
      - auth_api
